name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'examples/*'
      - 'extra/*'
      - 'docs/*'
      - 'docs-src/*'
      - 'mkdocs.yml'
  pull_request:
  schedule:
    - cron: '0 12 1 * *'
jobs:
  test:
    name: Checks/Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        # Add 'snapshot' to test on Emacs master
        emacs_version:
          - '26.3'
          - '29.2'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            emacs_version: '26.3'
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      - name: Setup checks
        run: 'make setup-check'
      - name: Run checks
        run: 'make check'
      - name: Setup unit testing
        run: 'make setup-tests'
      - name: Run ERT unit tests
        env:
          WAIT_TIME: 3
        run: 'make test'
